export const COMPLETION_HELP = `kb completion — generate shell completion scripts

Usage:
  kb completion bash
  kb completion zsh
  kb completion fish

Shells:
  bash                  Print a bash completion function for the \`kb\` command.
  zsh                   Print a zsh completion function for the \`kb\` command.
  fish                  Print fish completion commands for the \`kb\` command.

Options:
  --help, -h            Show this help.

Examples:
  kb completion bash > ~/.local/share/bash-completion/completions/kb
  kb completion zsh > ~/.zfunc/_kb
  kb completion fish > ~/.config/fish/completions/kb.fish
`;

export interface CompletionOption {
  flags: string[];
  value: string | null;
  description: string;
}

export interface CompletionCommand {
  name: string;
  summary: string;
  usage: string[];
  options: CompletionOption[];
}

export type CompletionShell = 'bash' | 'zsh' | 'fish';

type DynamicCompletionKind = 'kb' | 'model' | 'llm_profile';

const EMBEDDING_MODEL_OPTION_COMMANDS = new Set([
  'ask',
  'backup',
  'diff-index',
  'eval',
  'explain',
  'promote',
  'search',
  'superseded',
  'verify',
  'where',
]);

export async function runCompletion(
  rest: string[],
  commands: CompletionCommand[],
): Promise<number> {
  if (rest.length !== 1) {
    process.stderr.write('kb completion: expected one shell (bash, zsh, fish)\n');
    return 2;
  }
  const shell = rest[0];
  if (shell !== 'bash' && shell !== 'zsh' && shell !== 'fish') {
    process.stderr.write(`kb completion: unsupported shell '${shell}' (expected bash, zsh, or fish)\n`);
    return 2;
  }
  process.stdout.write(generateCompletionScript(shell, commands));
  return 0;
}

export function generateCompletionScript(shell: CompletionShell, commands: CompletionCommand[]): string {
  switch (shell) {
    case 'bash': return generateBashCompletion(commands);
    case 'zsh': return generateZshCompletion(commands);
    case 'fish': return generateFishCompletion(commands);
  }
}

function generateBashCompletion(commands: CompletionCommand[]): string {
  const commandWords = ['help', ...commands.map((command) => command.name)].sort().join(' ');
  const dynamicCases = bashDynamicCases(commands);
  const commandCases = commands.map((command) => (
    `    ${command.name})\n` +
    `      _kb_compgen ${shellSingleQuote(completionWordsForCommand(command).join(' '))}\n` +
    '      ;;\n'
  )).join('');
  return `# bash completion for kb; generated by \`kb completion bash\`
_kb() {
  local cur command prev value_prefix
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev=""
  value_prefix=""

  _kb_compgen() {
    COMPREPLY=( $(compgen -W "$1" -- "$cur") )
    if [[ -n "$value_prefix" ]]; then
      local i
      for i in "\${!COMPREPLY[@]}"; do
        COMPREPLY[$i]="\${COMPREPLY[$i]#"$value_prefix"}"
      done
    fi
  }

  _kb_dynamic_kind() {
    case "$1:$2" in
${dynamicCases}      *)
        return 1
        ;;
    esac
  }

  _kb_dynamic_values() {
    case "$1" in
      kb)
        command kb list 2>/dev/null
        ;;
      model)
        command kb models list 2>/dev/null | awk '/^\\*/ { print $2; next } /^[^([]/ { print $1 }'
        ;;
      llm_profile)
        command kb llm status 2>/dev/null | awk '/^[A-Za-z0-9_.-]+[[:space:]]/ { print $1 }'
        ;;
      *)
        return 1
        ;;
    esac
  }

  _kb_complete_dynamic() {
    local flag kind values original_cur value_cur
    flag=""
    value_cur="$cur"
    if [[ "$cur" == --*=* ]]; then
      flag="\${cur%%=*}"
      value_prefix="$flag="
      value_cur="\${cur#*=}"
    elif [[ "$prev" == --* ]]; then
      flag="$prev"
      value_prefix=""
    else
      return 1
    fi
    kind="$(_kb_dynamic_kind "$command" "$flag")" || return 1
    values="$(_kb_dynamic_values "$kind")" || return 1
    [[ -n "$values" ]] || return 1
    original_cur="$cur"
    cur="$value_cur"
    if [[ -n "$value_prefix" ]]; then
      values="$(printf '%s\\n' $values | sed "s#^#$value_prefix#")"
      cur="$value_prefix$value_cur"
    fi
    _kb_compgen "$values"
    cur="$original_cur"
    return 0
  }

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    _kb_compgen ${shellSingleQuote(commandWords)}
    return 0
  fi

  if [[ \${COMP_CWORD} -gt 0 ]]; then
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
  fi
  if [[ "$prev" == --* && "$COMP_LINE" == *"$prev=$cur"* ]]; then
    value_prefix="$prev="
    cur="$value_prefix$cur"
  fi

  command="\${COMP_WORDS[1]}"
  if _kb_complete_dynamic; then
    return 0
  fi
  case "$command" in
${commandCases}    help)
      _kb_compgen ${shellSingleQuote(`${commandWords} --format=md --format=json`)}
      ;;
    *)
      ;;
  esac
}
complete -F _kb kb
`;
}

function generateZshCompletion(commands: CompletionCommand[]): string {
  const dynamicCases = zshDynamicCases(commands);
  const commandEntries = [
    { name: 'help', summary: 'Show top-level or command-specific help' },
    ...commands.map((command) => ({ name: command.name, summary: command.summary })),
  ]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((entry) => `    ${shellSingleQuote(`${entry.name}:${escapeZshDescription(entry.summary)}`)}`)
    .join('\n');
  const commandCases = commands.map((command) => {
    if (command.name === 'completion') {
      return `      completion)\n        _values 'shell' bash zsh fish\n        ;;\n`;
    }
    const optionEntries = completionWordsForCommand(command)
      .map((word) => `        ${shellSingleQuote(word)}`)
      .join('\n');
    return `      ${command.name})\n        local -a opts\n        opts=(\n${optionEntries}\n        )\n        _describe -t options 'kb ${command.name} options' opts\n        ;;\n`;
  }).join('');
  return `#compdef kb
# zsh completion for kb; generated by \`kb completion zsh\`
_kb() {
  _kb_dynamic_kind() {
    case "$1:$2" in
${dynamicCases}      *)
        return 1
        ;;
    esac
  }

  _kb_dynamic_values() {
    case "$1" in
      kb)
        command kb list 2>/dev/null
        ;;
      model)
        command kb models list 2>/dev/null | awk '/^\\*/ { print $2; next } /^[^([]/ { print $1 }'
        ;;
      llm_profile)
        command kb llm status 2>/dev/null | awk '/^[A-Za-z0-9_.-]+[[:space:]]/ { print $1 }'
        ;;
      *)
        return 1
        ;;
    esac
  }

  local -a commands
  commands=(
${commandEntries}
  )
  local curcontext="$curcontext" state line
  _arguments -C \\
    '1:command:->commands' \\
    '*::argument:->arguments'

  case "$state" in
    commands)
      _describe -t commands 'kb commands' commands
      ;;
    arguments)
      local flag kind value_prefix
      if [[ "$words[CURRENT]" == --*=* ]]; then
        flag="\${words[CURRENT]%%=*}"
        value_prefix="$flag="
      elif [[ "$words[CURRENT-1]" == --* ]]; then
        flag="$words[CURRENT-1]"
        value_prefix=""
      fi
      if [[ -n "$flag" ]]; then
        kind="$(_kb_dynamic_kind "$line[1]" "$flag")"
        if [[ -n "$kind" ]]; then
          local -a dynamic_values
          dynamic_values=(\${(f)"$(_kb_dynamic_values "$kind")"})
          if [[ \${#dynamic_values[@]} -gt 0 ]]; then
            if [[ -n "$value_prefix" ]]; then
              dynamic_values=(\${^dynamic_values/#/$value_prefix})
            fi
            _values "$flag" $dynamic_values
            return
          fi
        fi
      fi
      case "$line[1]" in
${commandCases}      help)
        _describe -t commands 'kb commands' commands
        ;;
      esac
      ;;
  esac
}
_kb "$@"
`;
}

function generateFishCompletion(commands: CompletionCommand[]): string {
  const lines = [
    '# fish completion for kb; generated by `kb completion fish`',
    'complete -c kb -f',
    fishCompletionLine('__fish_use_subcommand', 'help', 'Show top-level or command-specific help'),
  ];
  for (const command of commands) {
    lines.push(fishCompletionLine('__fish_use_subcommand', command.name, command.summary));
  }
  const commandNames = commands.map((command) => command.name).join(' ');
  lines.push(`complete -c kb -n '__fish_seen_subcommand_from help' -a ${shellSingleQuote(commandNames)} -d 'Command'`);
  lines.push("complete -c kb -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish' -d 'Shell'");
  for (const command of commands) {
    if (command.name === 'completion') continue;
    const actions = actionWordsForCommand(command);
    if (actions.length === 0) continue;
    lines.push(`complete -c kb -n ${shellSingleQuote(`__fish_seen_subcommand_from ${command.name}`)} -a ${shellSingleQuote(actions.join(' '))} -d 'Action'`);
  }
  for (const command of commands) {
    for (const option of command.options) {
      const line = fishOptionLine(command.name, option);
      if (line !== null) lines.push(line);
    }
  }
  return `${lines.join('\n')}\n`;
}

function completionWordsForCommand(command: CompletionCommand): string[] {
  const words = new Set<string>();
  for (const action of actionWordsForCommand(command)) words.add(action);
  for (const option of command.options) {
    for (const flag of option.flags) {
      words.add(flag);
      if (flag.startsWith('--')) {
        for (const value of enumOptionValues(option)) {
          words.add(`${flag}=${value}`);
        }
      }
    }
  }
  return [...words].sort();
}

function enumOptionValues(option: CompletionOption): string[] {
  if (option.value !== null && !option.value.includes('<') && !option.value.includes('>')) {
    const parts = option.value.split('|').map((part) => part.trim()).filter(Boolean);
    if (parts.length > 0) return parts;
  }
  const controlled = /Controlled vocabulary:\s*([A-Za-z0-9_-]+(?:,\s*[A-Za-z0-9_-]+)+)/.exec(option.description);
  if (controlled === null) return [];
  return controlled[1].split(',').map((part) => part.trim()).filter(Boolean);
}

function actionWordsForCommand(command: CompletionCommand): string[] {
  const actions = new Set<string>();
  const prefix = `kb ${command.name} `;
  for (const usage of command.usage) {
    if (!usage.startsWith(prefix)) continue;
    const token = usage.slice(prefix.length).trim().split(/\s+/, 1)[0] ?? '';
    for (const part of token.split('|')) {
      if (isLiteralActionWord(part)) actions.add(part);
    }
  }
  return [...actions].sort();
}

function isLiteralActionWord(value: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9-]*$/.test(value);
}

function fishCompletionLine(condition: string, argument: string, description: string): string {
  return `complete -c kb -n ${shellSingleQuote(condition)} -a ${shellSingleQuote(argument)} -d ${shellSingleQuote(description)}`;
}

function fishOptionLine(commandName: string, option: CompletionOption): string | null {
  const switches = option.flags
    .map((flag) => {
      if (flag.startsWith('--') && flag.length > 2) return `-l ${shellSingleQuote(flag.slice(2))}`;
      if (/^-[A-Za-z0-9]$/.test(flag)) return `-s ${shellSingleQuote(flag.slice(1))}`;
      return null;
    })
    .filter((part): part is string => part !== null)
    .join(' ');
  if (switches === '') return null;
  const dynamicCommand = dynamicFishCommand(commandName, option);
  const enumValues = enumOptionValues(option);
  const valuePart = dynamicCommand !== null
    ? ` -a ${dynamicCommand}`
    : enumValues.length > 0
    ? ` -a ${shellSingleQuote(enumValues.join(' '))}`
    : '';
  const descriptionPart = option.description === '' ? '' : ` -d ${shellSingleQuote(option.description)}`;
  return `complete -c kb -n ${shellSingleQuote(`__fish_seen_subcommand_from ${commandName}`)} ${switches}${valuePart}${descriptionPart}`;
}

function dynamicCompletionKind(commandName: string, option: CompletionOption): DynamicCompletionKind | null {
  // Keep this mapping narrow: `--model` can mean an embedding model, a chat
  // model, or a local GGUF path depending on the command.
  if (option.flags.includes('--kb') || option.flags.includes('--include-kb') || option.flags.includes('--exclude-kb')) {
    return 'kb';
  }
  if (option.flags.includes('--llm-profile') || (commandName === 'llm' && option.flags.includes('--profile'))) {
    return 'llm_profile';
  }
  if (EMBEDDING_MODEL_OPTION_COMMANDS.has(commandName) && option.flags.includes('--model')) {
    return 'model';
  }
  return null;
}

function bashDynamicCases(commands: CompletionCommand[]): string {
  return dynamicCaseEntries(commands)
    .map((entry) => `      ${entry.pattern})\n        printf '%s\\n' ${entry.kind}\n        ;;\n`)
    .join('');
}

function zshDynamicCases(commands: CompletionCommand[]): string {
  return dynamicCaseEntries(commands)
    .map((entry) => `      ${entry.pattern})\n        print -r -- ${entry.kind}\n        ;;\n`)
    .join('');
}

function dynamicCaseEntries(commands: CompletionCommand[]): Array<{ pattern: string; kind: DynamicCompletionKind }> {
  const entries: Array<{ pattern: string; kind: DynamicCompletionKind }> = [];
  for (const command of commands) {
    for (const option of command.options) {
      const kind = dynamicCompletionKind(command.name, option);
      if (kind === null) continue;
      for (const flag of option.flags) {
        if (!flag.startsWith('--')) continue;
        entries.push({ pattern: `${command.name}:${flag}`, kind });
      }
    }
  }
  return entries.sort((a, b) => a.pattern.localeCompare(b.pattern));
}

function dynamicFishCommand(commandName: string, option: CompletionOption): string | null {
  const kind = dynamicCompletionKind(commandName, option);
  if (kind === 'kb') return "'(kb list 2>/dev/null)'";
  if (kind === 'model') {
    return "'(kb models list 2>/dev/null | awk '\\''/^\\\\*/ { print $2; next } /^[^([]/ { print $1 }'\\'')'";
  }
  if (kind === 'llm_profile') {
    return "'(kb llm status 2>/dev/null | awk '\\''/^[A-Za-z0-9_.-]+[[:space:]]/ { print $1 }'\\'')'";
  }
  return null;
}

function escapeZshDescription(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/:/g, '\\:');
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
