import { describe, expect, it } from '@jest/globals';
import { spawnSync } from 'child_process';

import {
  type CompletionCommand,
  generateCompletionScript,
} from './cli-completion.js';

const fixtureCommands: CompletionCommand[] = [
  {
    name: 'alpha',
    summary: 'Alpha: run local KB tasks',
    usage: [
      'kb alpha sync|status [options]',
      'kb alpha <path>',
    ],
    options: [
      {
        flags: ['--format', '-f'],
        value: 'md|json',
        description: "Writer's output format.",
      },
      {
        flags: ['--mode'],
        value: null,
        description: 'Controlled vocabulary: quick, full-scan',
      },
      {
        flags: ['--path'],
        value: '<file>',
        description: '',
      },
    ],
  },
  {
    name: 'completion',
    summary: 'Generate shell completions',
    usage: [
      'kb completion bash',
      'kb completion zsh',
      'kb completion fish',
    ],
    options: [
      {
        flags: ['--help', '-h'],
        value: null,
        description: 'Show completion help.',
      },
    ],
  },
];

describe('generateCompletionScript', () => {
  it('generates the bash completion golden script', () => {
    expect(generateCompletionScript('bash', fixtureCommands)).toBe(`# bash completion for kb; generated by \`kb completion bash\`
_kb() {
  local cur command prev value_prefix
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev=""
  value_prefix=""

  _kb_compgen() {
    COMPREPLY=( $(compgen -W "$1" -- "$cur") )
    if [[ -n "$value_prefix" ]]; then
      local i
      for i in "\${!COMPREPLY[@]}"; do
        COMPREPLY[$i]="\${COMPREPLY[$i]#"$value_prefix"}"
      done
    fi
  }

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    _kb_compgen 'alpha completion help'
    return 0
  fi

  if [[ \${COMP_CWORD} -gt 0 ]]; then
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
  fi
  if [[ "$prev" == --* && "$COMP_LINE" == *"$prev=$cur"* ]]; then
    value_prefix="$prev="
    cur="$value_prefix$cur"
  fi

  command="\${COMP_WORDS[1]}"
  case "$command" in
    alpha)
      _kb_compgen '--format --format=json --format=md --mode --mode=full-scan --mode=quick --path -f status sync'
      ;;
    completion)
      _kb_compgen '--help -h bash fish zsh'
      ;;
    help)
      _kb_compgen 'alpha completion help --format=md --format=json'
      ;;
    *)
      ;;
  esac
}
complete -F _kb kb
`);
  });

  it('generates the zsh completion golden script', () => {
    expect(generateCompletionScript('zsh', fixtureCommands)).toBe(`#compdef kb
# zsh completion for kb; generated by \`kb completion zsh\`
_kb() {
  local -a commands
  commands=(
    'alpha:Alpha\\: run local KB tasks'
    'completion:Generate shell completions'
    'help:Show top-level or command-specific help'
  )
  local curcontext="$curcontext" state line
  _arguments -C \\
    '1:command:->commands' \\
    '*::argument:->arguments'

  case "$state" in
    commands)
      _describe -t commands 'kb commands' commands
      ;;
    arguments)
      case "$line[1]" in
      alpha)
        local -a opts
        opts=(
        '--format'
        '--format=json'
        '--format=md'
        '--mode'
        '--mode=full-scan'
        '--mode=quick'
        '--path'
        '-f'
        'status'
        'sync'
        )
        _describe -t options 'kb alpha options' opts
        ;;
      completion)
        _values 'shell' bash zsh fish
        ;;
      help)
        _describe -t commands 'kb commands' commands
        ;;
      esac
      ;;
  esac
}
_kb "$@"
`);
  });

  it('generates the fish completion golden script', () => {
    expect(generateCompletionScript('fish', fixtureCommands)).toBe(`# fish completion for kb; generated by \`kb completion fish\`
complete -c kb -f
complete -c kb -n '__fish_use_subcommand' -a 'help' -d 'Show top-level or command-specific help'
complete -c kb -n '__fish_use_subcommand' -a 'alpha' -d 'Alpha: run local KB tasks'
complete -c kb -n '__fish_use_subcommand' -a 'completion' -d 'Generate shell completions'
complete -c kb -n '__fish_seen_subcommand_from help' -a 'alpha completion' -d 'Command'
complete -c kb -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish' -d 'Shell'
complete -c kb -n '__fish_seen_subcommand_from alpha' -a 'status sync' -d 'Action'
complete -c kb -n '__fish_seen_subcommand_from alpha' -l 'format' -s 'f' -a 'md json' -d 'Writer'\\''s output format.'
complete -c kb -n '__fish_seen_subcommand_from alpha' -l 'mode' -a 'quick full-scan' -d 'Controlled vocabulary: quick, full-scan'
complete -c kb -n '__fish_seen_subcommand_from alpha' -l 'path'
complete -c kb -n '__fish_seen_subcommand_from completion' -l 'help' -s 'h' -d 'Show completion help.'
`);
  });

  it('keeps bash enum completions working after Bash splits --flag=value input', () => {
    const result = spawnSync('bash', ['-c', [
      'eval "$KB_COMPLETION_SCRIPT"',
      'COMP_WORDS=(kb alpha --format js)',
      'COMP_CWORD=3',
      "COMP_LINE='kb alpha --format=js'",
      'COMP_POINT=${#COMP_LINE}',
      '_kb',
      'printf "%s\\n" "${COMPREPLY[@]}"',
    ].join('\n')], {
      env: {
        PATH: process.env.PATH ?? '',
        KB_COMPLETION_SCRIPT: generateCompletionScript('bash', fixtureCommands),
      },
      encoding: 'utf-8',
    });

    if (result.error) throw result.error;

    expect(result.status).toBe(0);
    expect(result.stderr).toBe('');
    expect(result.stdout.trim().split('\n')).toContain('json');
  });
});
