import { describe, expect, it } from '@jest/globals';
import { spawnSync } from 'child_process';

import {
  type CompletionCommand,
  generateCompletionScript,
} from './cli-completion.js';

const fixtureCommands: CompletionCommand[] = [
  {
    name: 'alpha',
    summary: 'Alpha: run local KB tasks',
    usage: [
      'kb alpha sync|status [options]',
      'kb alpha <path>',
    ],
    options: [
      {
        flags: ['--format', '-f'],
        value: 'md|json',
        description: "Writer's output format.",
      },
      {
        flags: ['--mode'],
        value: null,
        description: 'Controlled vocabulary: quick, full-scan',
      },
      {
        flags: ['--path'],
        value: '<file>',
        description: '',
      },
    ],
  },
  {
    name: 'completion',
    summary: 'Generate shell completions',
    usage: [
      'kb completion bash',
      'kb completion zsh',
      'kb completion fish',
    ],
    options: [
      {
        flags: ['--help', '-h'],
        value: null,
        description: 'Show completion help.',
      },
    ],
  },
];

describe('generateCompletionScript', () => {
  it('generates the bash completion script with static commands and dynamic helper hooks', () => {
    const script = generateCompletionScript('bash', fixtureCommands);

    expect(script).toContain("_kb_compgen 'alpha completion help'");
    expect(script).toContain("_kb_compgen '--format --format=json --format=md --mode --mode=full-scan --mode=quick --path -f status sync'");
    expect(script).toContain('_kb_dynamic_values()');
    expect(script).toContain('command kb list 2>/dev/null');
    expect(script).toContain('command kb models list 2>/dev/null');
    expect(script).toContain('command kb llm status 2>/dev/null');
    expect(script).toContain('if _kb_complete_dynamic; then');
  });

  it('generates the zsh completion script with static commands and dynamic helper hooks', () => {
    const script = generateCompletionScript('zsh', fixtureCommands);

    expect(script).toContain("'alpha:Alpha\\: run local KB tasks'");
    expect(script).toContain("'completion:Generate shell completions'");
    expect(script).toContain("_describe -t options 'kb alpha options' opts");
    expect(script).toContain('_kb_dynamic_values()');
    expect(script).toContain('command kb list 2>/dev/null');
    expect(script).toContain('dynamic_values=(${(f)"$(_kb_dynamic_values "$kind")"})');
  });

  it('generates the fish completion golden script', () => {
    expect(generateCompletionScript('fish', fixtureCommands)).toBe(`# fish completion for kb; generated by \`kb completion fish\`
complete -c kb -f
complete -c kb -n '__fish_use_subcommand' -a 'help' -d 'Show top-level or command-specific help'
complete -c kb -n '__fish_use_subcommand' -a 'alpha' -d 'Alpha: run local KB tasks'
complete -c kb -n '__fish_use_subcommand' -a 'completion' -d 'Generate shell completions'
complete -c kb -n '__fish_seen_subcommand_from help' -a 'alpha completion' -d 'Command'
complete -c kb -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish' -d 'Shell'
complete -c kb -n '__fish_seen_subcommand_from alpha' -a 'status sync' -d 'Action'
complete -c kb -n '__fish_seen_subcommand_from alpha' -l 'format' -s 'f' -a 'md json' -d 'Writer'\\''s output format.'
complete -c kb -n '__fish_seen_subcommand_from alpha' -l 'mode' -a 'quick full-scan' -d 'Controlled vocabulary: quick, full-scan'
complete -c kb -n '__fish_seen_subcommand_from alpha' -l 'path'
complete -c kb -n '__fish_seen_subcommand_from completion' -l 'help' -s 'h' -d 'Show completion help.'
`);
  });

  it('keeps bash enum completions working after Bash splits --flag=value input', () => {
    const result = spawnSync('bash', ['-c', [
      'eval "$KB_COMPLETION_SCRIPT"',
      'COMP_WORDS=(kb alpha --format js)',
      'COMP_CWORD=3',
      "COMP_LINE='kb alpha --format=js'",
      'COMP_POINT=${#COMP_LINE}',
      '_kb',
      'printf "%s\\n" "${COMPREPLY[@]}"',
    ].join('\n')], {
      env: {
        PATH: process.env.PATH ?? '',
        KB_COMPLETION_SCRIPT: generateCompletionScript('bash', fixtureCommands),
      },
      encoding: 'utf-8',
    });

    if (result.error) throw result.error;

    expect(result.status).toBe(0);
    expect(result.stderr).toBe('');
    expect(result.stdout.trim().split('\n')).toContain('json');
  });

  it('wires live value completions for KBs, embedding models, and LLM profiles', () => {
    const dynamicCommands: CompletionCommand[] = [
      {
        name: 'ask',
        summary: 'Ask a question',
        usage: ['kb ask <query> [options]'],
        options: [
          { flags: ['--kb'], value: '<name>', description: 'Scope retrieval to one knowledge base.' },
          { flags: ['--model'], value: '<id>', description: 'Override the active embedding model.' },
          { flags: ['--llm-profile'], value: '<name>', description: 'Use a saved `kb llm` profile.' },
        ],
      },
      {
        name: 'llm',
        summary: 'Manage local LLM endpoints',
        usage: ['kb llm status [--profile=<name>]'],
        options: [
          { flags: ['--profile'], value: '<name>', description: 'Saved LLM profile.' },
          { flags: ['--model'], value: '<gguf-path>', description: 'Local GGUF model path.' },
        ],
      },
      {
        name: 'eval-gate',
        summary: 'Run relevance-gate validation',
        usage: ['kb eval-gate run [--model=<id>]'],
        options: [
          { flags: ['--model'], value: '<id>', description: 'Model id passed to the endpoint.' },
        ],
      },
    ];

    const bash = generateCompletionScript('bash', dynamicCommands);
    expect(bash).toContain('ask:--kb)');
    expect(bash).toContain('ask:--model)');
    expect(bash).toContain('ask:--llm-profile)');
    expect(bash).toContain('llm:--profile)');
    expect(bash).not.toContain('llm:--model)');
    expect(bash).not.toContain('eval-gate:--model)');

    const fish = generateCompletionScript('fish', dynamicCommands);
    expect(fish).toContain("complete -c kb -n '__fish_seen_subcommand_from ask' -l 'kb' -a '(kb list 2>/dev/null)'");
    expect(fish).toContain("complete -c kb -n '__fish_seen_subcommand_from ask' -l 'model' -a '(kb models list 2>/dev/null");
    expect(fish).toContain("complete -c kb -n '__fish_seen_subcommand_from ask' -l 'llm-profile' -a '(kb llm status 2>/dev/null");
    expect(fish).toContain("complete -c kb -n '__fish_seen_subcommand_from llm' -l 'profile' -a '(kb llm status 2>/dev/null");
    expect(fish).toContain("complete -c kb -n '__fish_seen_subcommand_from llm' -l 'model' -d 'Local GGUF model path.'");
    expect(fish).toContain("complete -c kb -n '__fish_seen_subcommand_from eval-gate' -l 'model' -d 'Model id passed to the endpoint.'");
  });

  it('completes live bash --flag=value values from safe local kb subcommands', () => {
    const dynamicCommands: CompletionCommand[] = [
      {
        name: 'ask',
        summary: 'Ask a question',
        usage: ['kb ask <query> [options]'],
        options: [
          { flags: ['--kb'], value: '<name>', description: 'Scope retrieval to one knowledge base.' },
          { flags: ['--model'], value: '<id>', description: 'Override the active embedding model.' },
          { flags: ['--llm-profile'], value: '<name>', description: 'Use a saved `kb llm` profile.' },
        ],
      },
      {
        name: 'llm',
        summary: 'Manage local LLM endpoints',
        usage: ['kb llm status [--profile=<name>]'],
        options: [
          { flags: ['--profile'], value: '<name>', description: 'Saved LLM profile.' },
        ],
      },
    ];

    expect(runBashCompletion(dynamicCommands, 'COMP_WORDS=(kb ask --kb re)', 'kb ask --kb=re')).toContain('research');
    expect(runBashCompletion(dynamicCommands, 'COMP_WORDS=(kb ask --model open)', 'kb ask --model=open')).toContain('openai__text-embedding-3-small');
    expect(runBashCompletion(dynamicCommands, 'COMP_WORDS=(kb ask --llm-profile loc)', 'kb ask --llm-profile=loc')).toContain('local-research-agent');
    expect(runBashCompletion(dynamicCommands, 'COMP_WORDS=(kb llm --profile qw)', 'kb llm --profile=qw')).toContain('qwen');
  });
});

function runBashCompletion(commands: CompletionCommand[], compWordsAssignment: string, compLine: string): string[] {
  const result = spawnSync('bash', ['-c', [
    'tmpbin="$(mktemp -d)"',
    'trap \'rm -rf "$tmpbin"\' EXIT',
    'cat > "$tmpbin/kb" <<\'EOS\'',
    '#!/usr/bin/env bash',
    'if [[ "$1" == "list" ]]; then',
    '  printf "%s\\n" work research archive',
    'elif [[ "$1 $2" == "models list" ]]; then',
    '  printf "%s\\n" "* openai__text-embedding-3-small  openai       text-embedding-3-small" "  ollama__nomic-embed-text-latest  ollama       nomic-embed-text:latest"',
    'elif [[ "$1 $2" == "llm status" ]]; then',
    '  printf "%s\\n" "local-research-agent     external (local-research-agent)  http://127.0.0.1:8080/v1/chat/completions" "qwen                     managed kb-llm@qwen.service       http://127.0.0.1:8091/v1/chat/completions"',
    'fi',
    'EOS',
    'chmod +x "$tmpbin/kb"',
    'export PATH="$tmpbin:$PATH"',
    'eval "$KB_COMPLETION_SCRIPT"',
    compWordsAssignment,
    'COMP_CWORD=3',
    `COMP_LINE=${bashSingleQuote(compLine)}`,
    'COMP_POINT=${#COMP_LINE}',
    '_kb',
    'printf "%s\\n" "${COMPREPLY[@]}"',
  ].join('\n')], {
    env: {
      PATH: process.env.PATH ?? '',
      KB_COMPLETION_SCRIPT: generateCompletionScript('bash', commands),
    },
    encoding: 'utf-8',
  });

  if (result.error) throw result.error;
  expect(result.status).toBe(0);
  expect(result.stderr).toBe('');
  return result.stdout.trim().split('\n');
}

function bashSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
